Update perceptive flow design topic in Studio
mulesoft/docs-studio pull request #51
Opened 2019-05-23 15:34 UTC by fermujica

We need to make it clearer that metadata needs to be declared when the data is generated outside the scope of a reusable artifact. 
This concept needs to be introduced when the user is told the best practices for handling metadata in a Mule 4 application.

Additionally, I'm adding an example of how to solve the `unable to resolve reference` error that returns Studio when metadata expected by a component outside the flow where the data lives is not explicitly declared.

2019-05-23 15:52 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-perceptive-flow-design-concept.adoc
> +Consider a flow in which you included an Anypoint Connector that's preceded or followed by a Transform Message component. The Mule runtime engine uses the working connection to the resource to retrie
"...input or output, and avoiding you..." I think the **and** needs to be removed: "...input or output, avoiding you... "

2019-05-23 16:04 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-perceptive-flow-design-concept.adoc
> +Declaring a Flow Reference component that points to another flow with a Set Payload component right after an HTTP Lister source causes the Set Payload component to throw an `Unable to resolve referen
"HTTP Lister" > "Listener. This sentence is very long, can this be restructured to something like:
"If you declare a Flow Reference component that points to another flow with a Set Payload component right after an HTTP Listener source, the Set Payload component throws an `Unable to resolve reference` error.

2019-05-23 16:06 UTC, Cristian-Venticinque approved these changes

2019-05-28 17:33 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-perceptive-flow-design-concept.adoc
> +For example, the transform message component should not define a metadata contract because Dataweave acts as a data mediation device between the producer and consumer of data, Those boundaries are th
", Those" capitalization error. Change to either: ", those" or ". Those"

2019-05-28 17:35 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-perceptive-flow-design-concept.adoc
> +For example, the transform message component should not define a metadata contract because Dataweave acts as a data mediation device between the producer and consumer of data, Those boundaries are th
Transform Message shows capitalized in some instances and others don't, please check for consistency.

2019-06-04 07:56 UTC, pablocabrera85 approved these changes
Looks good to me.

2019-06-04 07:59 UTC, pablocabrera85 commented
Maybe we can also show the apikit router scenario. In this case, APIKit contributes to the metadata of the subflow that is scaffolded, but when users define that they want to use a flow ref and code the behaviour in another subflow without the name convention used by APIKit, they lose the metadata, and because it might be defined inline in the RAML, they cannot reuse it that easily

2019-06-04 11:00 UTC, fermujica commented
Interesting. I think this APIkit scenario makes more sense in the APIkit documentation, and then link from this topic to that. 
I'll merge this and create another issue to track the inclusion of the APIkit scenario.

2019-06-27 15:08 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-concept.adoc
> +Although all components of a Mule application allow you to manually define the metadata that they expose, you should do so only when it is absolutely required (for example, for a value being define b
typo: for a value being define **d** by you).
You can also void the passive voice > (for example, for a value you defined)

2019-06-27 15:14 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-concept.adoc
> +Understanding how your components use metadata in a flow is key to ensuring data reliability by enabling early detection of errors during project design and data reusability in your Mule application
This is one long sentence, can it be broken down? Maybe something like:
...is key to ensuring:
* data reliability, by enabling...
* data reusability, by detecting...

2019-06-27 15:19 UTC, Cristian-Venticinque commented on modules/ROOT/pages/datasense-concept.adoc
> +For example, when working with flows and subflows you must declare their metadata contract that specifies the shape of the event you require and the shape of the event your return to the caller. On t
declare their metadata contract that specifies, I think this needs to be modified to either:
* declare **the** metadata contract that specifies...
* declare their metadata contract **to specify**...

2019-06-27 15:23 UTC, Cristian-Venticinque requested changes
Please check

2019-06-27 20:13 UTC, Cristian-Venticinque approved these changes

2019-06-27 20:13 UTC, merged